services:
  - type: web
    name: nationforge
    env: node
    runtime: node
    nodeVersion: 18.x
    buildCommand: npm install && npm run build
    startCommand: npm start
    buildFilter:
      paths:
        - package.json
        - client/**
        - server/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        value: d8e027c3a47a2f18845b8b70d3c2b1e5f924a3d6b9c0e4f7a1d3b5c8e9f2a4d
      - key: PORT
        value: "10000"